### ISSUE TITLE
Can not select a folder

### ISSUE THREAD

**Issue by Tids** [flathub/org.nextcloud.Nextcloud#13]
If I try to add a new folder to the sync, the filedialog that pops up can not select folders, but files only. Wich makes it impossible to add folders.

**Comment by lachmanfrantisek** [comment]
Having the same problem on gnome/fedora 27.

As a workaround, you can skip the folder setup and after that, you can select the folder from the app window, where you can select the folder.

**Comment by juliushaertl** [comment]
Looks related tp https://gitlab.gnome.org/GNOME/gtk/issues/870 to me. The nextcloud client uses QFileDialog::getExistingDirectory which should from my understanding trigger a native file dialog using the xdg-desktop-portal. But that one doesn't seem to support selecting folders. 

Issue at xdg-desktop-portal https://github.com/flatpak/xdg-desktop-portal/issues/158

**Comment by juliushaertl** [comment]
Seems to be fixed with the latest Kde runtime: https://phabricator.kde.org/R257:6898c90da009dd6b6b6832951de35b9c10eb00c1

@Tids @lachmanfrantisek Can you try this again, with the runtime updated? 

Related issue at qButtorrent https://github.com/flathub/org.qbittorrent.qBittorrent/issues/7

**Comment by Tids** [comment]
@juliushaertl I'll ldo that but it could take a while since I need to wait for my CPU :)
