### ISSUE TITLE
Doesn't open at startup

### ISSUE THREAD

**Issue by plfiorini** [flathub/org.nextcloud.Nextcloud#18]
Even though it is configured to launch at startup it doesn't do that.

**Comment by TingPing** [comment]
Any autostart feature in a sandboxed application can't work. In this case it needs to be rewritten to launch via `flatpak` somehow.

**Comment by prog-amateur** [comment]
Hello, did you find a solution ? 
I am on Ubuntu Wayland. Any flatpak app I have installed can open, while Nextcloud can't. 
Today, I have sync issues, and I can't simply open the UI.

**Comment by juliushaertl** [comment]
Just found https://github.com/flatpak/flatpak/issues/118 so it is an upstream issue. However you can manually add the nextcloud client as an autostart application, either using gnome tweaks or with the following desktop file added to .config/autostart
