### ISSUE TITLE
OpenSSL 1.1 required for 2.5 release

### ISSUE THREAD

**Issue by juliushaertl** [flathub/org.nextcloud.Nextcloud#21]
For building the upcoming 2.5.0 release, we need to have openssl 1.1 available inside the flatpak.

**Comment by TingPing** [comment]
Once the KDE runtime rebases on fdo 18.08 you'll get it.

**Comment by juliushaertl** [comment]
Ah nice, thanks @TingPing for the information.

**Comment by monreal** [comment]
The 5.12 runtime should be based on fdo 18.08 now? See https://github.com/KDE/flatpak-kde-runtime/commit/cf897200a8b9011a416f9e00b4e155002b0d3d1a

Can you provide 2.5.x now?

**Comment by juliushaertl** [comment]
Thanks, I'll look into it.

**Comment by juliushaertl** [comment]
2.5 is merged with https://github.com/flathub/org.nextcloud.Nextcloud/pull/25

**Comment by monreal** [comment]
Thanks a lot!
