### ISSUE TITLE
Provided RC on beta repo

### ISSUE THREAD

**Issue by tilosp** [flathub/org.nextcloud.Nextcloud#30]
Flathub has a new beta repo: https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

This could be used to publish the current RC. But i can't open a pr because this requires a git branch called beta, which requires commit rights to create.

**Comment by juliushaertl** [comment]
@tilosp I cannot add you as a committer right now, so I created and pushed a branch.

**Comment by tilosp** [comment]
@juliushaertl i you want me to have commit rights you have to ask a flathub admin to give them.

**Comment by juliushaertl** [comment]
@TingPing @alexlarsson Can one of you add @tilosp as a contributor to this repo so he has commit rights?

**Comment by alexlarsson** [comment]
Added @tilosp , but you need to change the branch in the manifest to say "beta" in the beta branch.

**Comment by tilosp** [comment]
removing the branch name should also work, right?

**Comment by alexlarsson** [comment]
Yes, but then your local build is different. Actually the recommended thing is to use the new "default-branch". Then it will be overriddent by buildbot to either beta or test, but local builds with no args are built as what you want.
