### ISSUE TITLE
libaom.so.0 not found

### ISSUE THREAD

**Issue by geez0x1** [flathub/org.nextcloud.Nextcloud#35]
As of today I'm seeing this message trying to start the client through the flatpak package:
```
user@debian:~$ flatpak run org.nextcloud.Nextcloud
/app/bin/nextcloud: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory
```
I have verified `libaom.so.0` is available, both using `find` and `ldconfig -v`. I have not just updated the flatpak package - but I do still suspect the involvement of flatpak has to do with it. Any ideas?

A reinstallation of the package did not help (although I did not suspect it would).

**Comment by tilosp** [comment]
See: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709

**Comment by geez0x1** [comment]
Thanks for the reference @tilosp.

I can confirm this workaround mentioned there works for now:
```
flatpak update --commit=71faea5b07a69e755b0b3c3694aa5a8903d3a69b09994b0e8ebd8b60d2dc744f org.freedesktop.Platform.html5-codecs/x86_64/18.08
```
Obviously this results in the package being marked as update-able when running `flatpak update`, which I'll refrain from for now until the original issue is fixed.

**Comment by Erick555** [comment]
@geez0x1 the fix was published on flathub. Everything should work after `flatpak update`.

**Comment by geez0x1** [comment]
@Erick555: Can confirm :) Thanks for letting me know.
