### ISSUE TITLE
QtSingleApplication lock in /tmp should be shared

### ISSUE THREAD

**Issue by juliushaertl** [flathub/org.nextcloud.Nextcloud#4]
Otherwise it will cause in multiple instances running at the same time

**Comment by juliushaertl** [comment]
/tmp is per app, so the TMPDIR environment variable should be set to something shared for the nextcloud binary

**Comment by TingPing** [comment]
Something like: https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json#L48-L54

**Comment by juliushaertl** [comment]
Ah great, that looks good. I'll give it a try later today.

**Comment by juliushaertl** [comment]
Fixed with #6
