### ISSUE TITLE
crashes on first key press

### ISSUE THREAD

**Issue by Yvan-Masson** [flathub/org.nextcloud.Nextcloud#5]
Hi,

Thanks for providing this package.

When I run it, the server configuration windows appears, but as soon as I type a key, the software quits. Running it from command line, it get this output:

```
$ flatpak -v run org.nextcloud.Nextcloud/x86_64/stable
XA: Opening user flatpak installation at path /home/yvan/.local/share/flatpak
XA: No installations directory in /etc/flatpak/installations.d. Skipping
XA: Opening system flatpak installation at path /var/lib/flatpak
XA: Opening user flatpak installation at path /home/yvan/.local/share/flatpak
XA: Opening system flatpak installation at path /var/lib/flatpak
XA: Allowing homedir access
XA: Allowing x11 access

(process:3): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
```
I am running Gnome 3.26 on Wayland on Debian testing. I am going to test this under Xorg and let you know. I you think I should report this issue somewhere else, do not hesitate to tell.

Regards,
Yvan

**Comment by TingPing** [comment]
Hmm, does `flatpak run --device=dri org.nextcloud.Nextcloud` change anything?

**Comment by Yvan-Masson** [comment]
> Hmm, does flatpak run --device=dri org.nextcloud.Nextcloud change anything?

Thanks for the answer, but unfortunately no. I still have to test this under Xorg.

**Comment by Yvan-Masson** [comment]
I can confirm that this problem also occurs when running Gnome on Xorg.

**Comment by juliushaertl** [comment]
@Yvan-Masson Can you also check the log files of the nextcloud client?

```
flatpak run org.nextcloud.Nextcloud --logfile nextcloud-log.txt
```

**Comment by Yvan-Masson** [comment]
Here it is:
[nextcloud-log.txt](https://github.com/flathub/org.nextcloud.Nextcloud/files/1495319/nextcloud-log.txt)

**Comment by Yvan-Masson** [comment]
Hi,

Last updates proposed by Gnome Software have fixed this issue.

Regards,
Yvan

**Comment by Yvan-Masson** [comment]
Hi,

Last updates proposed by Gnome Software have fixed this issue.

Regards,
Yvan
