### ISSUE TITLE
No tray icon in Gnome 3.32.2 even with tray extensions

### ISSUE THREAD

**Issue by penyuan** [flathub/org.nextcloud.Nextcloud#62]
Hello,

I installed the Nextcloud client Flatpak from Flathub via Gnome Software running on Gnome 3.32.2 in a RHEL 8.1 system. Not sure if it is related to [issue #56](https://github.com/flathub/org.nextcloud.Nextcloud/issues/56) but for the life of me I can't get the Nextcloud tray icon to show up.

Things I've tried:

1. Installing the `libappindicator-gtk3` package (the only `libappindicator` package in my distributions repositories).

2. Trying many Gnome tray icon extensions including `Kstatusnotifieritem/appindicator support`, `Top icons`, `Topicons Redux`, etc.

3. I tried running the command `flatpak override --user --own-name=org.kde.* org.nextcloud.Nextcloud` as suggested in issue #56 from a `bash` prompt but it had no effect, and Nextcloud didn't even start.

I noticed that with the tray extensions on, the Nextcloud client would start and show its window (but no tray icon). Once I installed `libappindicator-gtk3` with the extensions still activated, the Nextcloud client window doesn't even show up! I can see the `nextcloud` process running, but with absolutely no access to the GUI it is highly problematic.

Right now, I need to turn the tray extensions off and leave the Nextcloud window open in order to keep it running.

Can anyone advise on how to troubleshoot and solve this annoying problem? Thank you!

**Comment by barthalion** [comment]
Can you try running it with `--own-name=org.kde.*`?

**Comment by barthalion** [comment]
Does any other application have tray icon working?

**Comment by penyuan** [comment]
Thanks for getting back to me!

> Does any other application have tray icon working?

Yes, other applications such as Skype are able to show their tray icons.

I've also made another discovery: I disabled Wayland and made Gnome use Xorg instead. Now the Nextcloud tray icon shows up! What does this mean? And since Gnome is moving towards Wayland, is there a way to get the tray icon to show up in Gnome Wayland mode?

**Comment by Iolaum** [comment]
Using Fedora SilverBlue 32, with `gnome-shell-extension-appindicator` enabled and the nextcloud tray icon is not showing. In normal Fedora 32 with `nextcloud-client` installed as an rpm package the tray icon is showing.

**Comment by penyuan** [comment]
> Using Fedora SilverBlue 32, with `gnome-shell-extension-appindicator` enabled and the nextcloud tray icon is not showing. In normal Fedora 32 with `nextcloud-client` installed as an rpm package the tray icon is showing.

Is your Gnome in Wayland or X mode? What happens in each? (for me, I can only see the tray icon when Gnome is set to X mode)

**Comment by Iolaum** [comment]
I had the same problem when I loggin in at an x11 session in Fedora SilverBlue 32 while running nextcloud-client from flatpak.

**Comment by penyuan** [comment]
> I had the same problem when I loggin in at an x11 session

That's unfortunate. Sorry I'm just a user and don't really know what might be causing the problem.

Since Gnome is moving towards Wayland and one day X will likely become unsupported, I think this issue should be solved. Can any of the maintainers and/or developers provide some insight?

**Comment by juliushaertl** [comment]
@wjt provided a possible fix for this.

Testing is very welcome https://github.com/flathub/org.nextcloud.Nextcloud/pull/67#issuecomment-658801963

**Comment by returntrip** [comment]
> @wjt provided a possible fix for this.
> 
> Testing is very welcome [#67 (comment)](https://github.com/flathub/org.nextcloud.Nextcloud/pull/67#issuecomment-658801963)


`error: Can't load uri https://dl.flathub.org/build-repo/22853/org.nextcloud.Nextcloud.flatpakref: Server returned status 404: Not Found`
