### ISSUE TITLE
Integration of file manager extensions

### ISSUE THREAD

**Issue by linuxrider** [flathub/org.nextcloud.Nextcloud#8]
What would be the right way to get the nautilus working with this flatpak?
nautilus extension from ubuntu repository requires the client from the repo to be installed.

**Comment by juliushaertl** [comment]
The Nextcloud client uses a socket file to communicate between the nautilus extension and the client iirc. That needs to be available to the flatpak environment.

**Comment by linuxrider** [comment]
I could get it to work with the following command:
flatpak --user override --filesystem=$XDG_RUNTIME_DIR/Nextcloud org.nextcloud.Nextcloud
Would it make sense to give this permission by default?

Another point is the nautilus extension. For now I use the extension from the nextcloud ppa which forces me to have also the system nextcloud client installed.

**Comment by TingPing** [comment]
> I could get it to work with the following command:
flatpak --user override --filesystem=$XDG_RUNTIME_DIR/Nextcloud org.nextcloud.Nextcloud
Would it make sense to give this permission by default?

Sounds reasonable to me. It should be `--filesystem=$XDG_RUNTIME_DIR/Nextcloud:create` though as the directory may not exist.

**Comment by juliushaertl** [comment]
> Would it make sense to give this permission by default?

That would make sense. Let me add that.

**Comment by lachmanfrantisek** [comment]
Hi all!

I've spent some hours trying to make the nautilus extension work, but without success... Just want to ask for help with that.

#### System
- System: Fedora Atomic Workstation 27
- Desktop: Gnome 3.26.2
- Nautilus: 3.26.2

I've installed flatpak version as well as the normal one (only for the nautilus script). After installing some dependencies, nautilus starts the script and shows the following log:

```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Initializing Nextcloud-client-nautilus extension
Socket File: /run/user/1000/Nextcloud/socket
Setting connectedčis to True.
Socket watch id: 12
Server response: REGISTER_PATH:/var/home/flachman
Server response: STATUS:OK:/var/home/flachman
``` 

But the file emblems and the context menu are missing. Do you know, where can be a problem?

Thanks in advance.

**Comment by lachmanfrantisek** [comment]
@juliushaertl Could you help me with this, please? Thanks!

**Comment by juliushaertl** [comment]
@lachmanfrantisek So according to the nautilus log, the connection between the nautilus plugin and the client works fine: 
```
Socket watch id: 12
Server response: REGISTER_PATH:/var/home/flachman
Server response: STATUS:OK:/var/home/flachman
```

Not sure about the nautilus script from the normal package, bug you could try installing the script only from the sources: https://github.com/owncloud/client/blob/57bc7918d7b0650c116f3512787f7677d4e5ab17/shell_integration/nautilus/syncstate.py (You need to adjust the appname variable to 'Nextcloud')

**Comment by lachmanfrantisek** [comment]
@juliushaertl  Thanks for your tips. The version from your link is exactly the same as in the Fedora repository. 

I've found, that the "normal" package has this problem too -- there is probably some problem in the Atomic version of Fedora Workstation, so it is probably not related to the flatpaking.

Thank you.

**Comment by juliushaertl** [comment]
> I've found, that the "normal" package has this problem too -- there is probably some problem in the Atomic version of Fedora Workstation, so it is probably not related to the flatpaking.

Probably. It is running fine here with the script and Nextcloud flatpak on arch linux. Is nautilus running as a flatpak with the atomic version of fedora? Maybe there is a communication issue there.

**Comment by LorbusChris** [comment]
What is the status of this issue?
