### ISSUE TITLE
Nextcloud doesn't register tray icon

### ISSUE THREAD

**Issue by Firstyear** [flathub/org.nextcloud.Nextcloud#9]
Hi,

I've been really impressed by the flatpak of nextcloud, but sadly it doesn't have the tray icon available. This is a problem, as closing nextcloud keeps it running in the background, but without the tray icon there is no way to re-access the application. 

It would be great if nextcloud had the tray icon for the flatpak,

Thanks!

**Comment by TingPing** [comment]
Does `flatpak run --talk-name=org.kde.StatusNotifierWatcher org.nextcloud.Nextcloud` work for you?

**Comment by Firstyear** [comment]
No, this does not work :(

**Comment by Firstyear** [comment]
https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/ <<-- this may be the root cause of the problem. It seems you require gnome-shell-extension-topicons-plus.noarch to actually see status icons now. I'll add this and try again ...

**Comment by Firstyear** [comment]
Yes. Running nextcloud as ```flatpak run --talk-name=org.kde.StatusNotifierWatcher org.nextcloud.Nextcloud``` resolves the issue.

Running it without this does not present the icon.

How can this be made a default?

**Comment by cwmke** [comment]
I'm having the same issue but the above doesn't work for me. I get the below errors when I start the flatpak from the terminal.

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
```

**Comment by marxistvegan** [comment]
I am running Fedora 31 with the Gnome desktop, and with the tray extention i am not able to get nextcloud to show, I tried the` flatpak run --talk-name=org.kde.StatusNotifierWatcher org.nextcloud.Nextcloud` but no luck, wondering if there is a command for Gnome specifically?

**Comment by vasyugan** [comment]
I am running Debian Buster and there, the suggested parameter makes no difference either.
